version: "3.7"
services:
  web:
    image: nginx:latest
    container_name: web
    ports:
      - "8080:80"
    volumes:
      - ./src:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
        - service_php

# Previously used service
  # php:
  #   image: php:8-fpm
  #   container_name: php
  #   volumes:
  #     - ./src:/code


  # service_php:
  #   image: blog:latest
  #   build:
  #     context: ./
  #     dockerfile: docker/Dockerfile
  #   container_name: php
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./src:/code

  # service_postgresdb:
  #   image: postgres:14.3
  #   container_name: service_postgresdb
  #   environment:
  #     POSTGRES_ROOT_PASSWORD: root
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: site_blog
  #   ports:
  #     - "5431:5432"
  #   volumes:
  #     - /home/postgres_blog_db:/var/lib/postgresql/data

  # service_pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@unicourt.com
  #     - PGADMIN_DEFAULT_PASSWORD=password
  #   ports:
  #     - "8000:80"
  #   links:
  #     - service_postgresdb:postgress